// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvl_k2GYCTl4gzcCQ0RTeE6j_okJIYcpc',
    appId: '1:961743427049:web:3d8539747ab5836acca778',
    messagingSenderId: '961743427049',
    projectId: 'tenantapp-fyp',
    authDomain: 'tenantapp-fyp.firebaseapp.com',
    storageBucket: 'tenantapp-fyp.firebasestorage.app',
    measurementId: 'G-FBDP2QYDRE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZoBMpiAy6rfySUu9eQLj-zzjOXcgPmQY',
    appId: '1:961743427049:android:6c2a153c1beaba17cca778',
    messagingSenderId: '961743427049',
    projectId: 'tenantapp-fyp',
    storageBucket: 'tenantapp-fyp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAg8W6AXb3SN2ZUjfLFzz2rDlknaunV398',
    appId: '1:961743427049:ios:93a2f00218f0526ecca778',
    messagingSenderId: '961743427049',
    projectId: 'tenantapp-fyp',
    storageBucket: 'tenantapp-fyp.firebasestorage.app',
    iosBundleId: 'com.yixiang.tenant',
  );
}
